server:
  port: 9502
  servlet:
    context-path: /MicroService2

spring:
  application:
    name: USER-SERVICES
  datasource:
    url: jdbc:postgresql://localhost:5432/VishalDB
    username: postgres
    password: Vishal@91289

    
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost